---
  title: "Movie Statistics"
  author: "Victoria Wingo"
---
    
```{r data, include = FALSE}
library(ggplot2)
library(dplyr)
library(readr)
library(DataCombine)
library(tidyverse)
Highest_Hollywood_Grossing_Movies <- read.csv("Highest Hollywood Grossing Movies.csv")
```

## Datasets

### Movies

The `movies` dataset serves as a corrected version of the original dataset `Highest_Hollywood_Grossing_Movies` taken from kaggle. Missing data has been added and the variable `runtime` has been converted from the 00h 00m format to minutes.
```{r movies}
movies <- Highest_Hollywood_Grossing_Movies %>% 
  mutate(
    world_sales_mil = world_sales_dollars / 1000000, 
    release_year = format(as.Date(release_date, format="%B %d, %Y"),"%Y")) %>% 
  data.frame()

froms <- c(unique(movies$runtime))
tos <- c(138, 181, 162, 134, 149, 148, 194, 124, 143, 152, 118, 133, 141, 129, 
         97, 103, 136, 121, 164, 93, 115, 100, 123, 146, 151, 88, 128, 130, 147, 
         142, 119, 127, 102, 140, 201, 87, 98, 106, 108, 95, 137, 154, 179, 139, 
         91, 122, 135, 144, 126, 178, 169, 131, 145, 153, 107, 96, 92, 157, 117, 
         85, 104, 90, 89, 161, 101, 165, 105, 113, 116, 132, 120, 125, 84, 187, 
         86, 112, 94, 111, 183, 110, 155, 83, 156, 150, 81, 158, 163, 114, 109, 
         99, 82, 189, 175, 166, 180, 170, 79, 78, 195, 76, 77)
replaces <- data.frame(from = unique(movies$runtime), to = tos)
movies <- FindReplace(data = movies, 
                      Var = "runtime", 
                      replaceData = replaces, 
                      from = "from", 
                      to = "to", 
                      exact = TRUE) %>%
  transform(runtime = as.numeric(runtime))

# for the purposes of code demonstration
replacelicense <- c('PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 'G', 'PG-13', 'G', 
                   'PG', 'PG-13', 'PG-13', 'PG-13', 'PG', 'G', 'PG', 'PG', 
                   'PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 'G', 'G', 'PG', 
                   'PG-13', 'R', 'PG-13', 'PG-13', 'G', 'PG', 'G', 'PG-13', 'G', 
                   'PG-13', 'PG-13', 'PG', 'PG', 'PG-13', 'PG', 'G', 'PG-13', 
                   'NA', 'PG-13', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 'PG', 
                   'PG-13', 'PG', 'PG', 'PG-13', 'R', 'PG-13', 'PG', 'PG-13', 
                   'PG-13', 'G', 'PG-13', 'PG-13', 'R', 'PG', 'PG', 'G', 'G', 
                   'PG-13', 'R', 'PG-13', 'PG', 'G', 'PG-13', 'PG', 'G', 'R', 
                   'R', 'R', 'PG', 'R', 'PG', 'R', 'PG', 'PG-13', 'PG', 'PG-13', 
                   'PG-13', 'R', 'R', 'PG-13', 'PG', 'PG', 'R', 'PG-13', 'PG', 
                   'R', 'PG', 'PG', 'R', 'PG-13', 'PG-13', 'PG-13', 'PG', 'PG', 
                   'PG', 'R', 'PG', 'PG-13', 'PG-13', 'G', 'R', 'PG-13', 'PG-13', 
                   'PG', 'PG', 'G', 'PG', 'PG-13', 'PG', 'R', 'PG-13', 'PG-13', 
                   'G', 'PG', 'PG', 'G', 'G', 'G', 'PG-13', 'PG', 'G', 'PG', 'R', 
                   'PG-13', 'G', 'PG', 'PG', 'PG-13', 'R', 'PG-13', 'PG-13', 'R', 
                   'PG-13', 'PG-13', 'PG', 'PG-13', 'PG', 'PG-13', 'G', 'PG', 'R', 
                   'PG', 'PG-13', 'R', 'PG-13', 'PG', 'G', 'PG-13', 'R', 'R', 'R', 
                   'G', 'PG', 'PG-13', 'R', 'R', 'R', 'PG', 'R', 'PG', 'PG', 
                   'PG', 'R', 'PG-13', 'G')
ind <- which(is.na(movies$license))
replace_ind <- 1
for(x in ind){
  movies$license[x] <- replacelicense[replace_ind]
  replace_ind <- replace_ind +1
}
```

### Average Sales by Runtimes

```{r by_runtime}
by_runtime <- movies %>% group_by(runtime) %>% summarize(avgSales = mean(world_sales_mil))
ggplot(by_runtime, aes(x = runtime, y = avgSales)) + geom_point() + geom_smooth() + scale_y_continuous(name = "Average Sales (in millions)", breaks=seq(0,max(by_runtime$avgSales)+50, 100)) + scale_x_continuous(name = "Runtime (in minutes)", breaks=seq(min(by_runtime$runtime)- 10, max(by_runtime$runtime)+10, 30))
```

### Average Sales by License

```{r sales_by_license}
sales_by_license <- movies %>% group_by(license) %>% summarize(avgSales = mean(world_sales_mil))
ggplot(sales_by_license, aes(x = license, y = avgSales)) + geom_col() + scale_y_continuous(name = "Average Sales (in millions)", breaks=seq(0,max(sales_by_license$avgSales)+50, 100)) + scale_x_discrete(name = "License")
```

### Average Runtimes by License

```{r by_license}
by_license <- movies %>% group_by(license) %>% summarize(avgRuntime = mean(runtime))
ggplot(by_license, aes(x = license, y = avgRuntime)) + geom_col() + scale_y_continuous(name = "Average Runtime (in minutes)", breaks=seq(0, 215, 30)) + scale_x_discrete(name = "License")
```

### Average Sales by Release Year
```{r by_year}
by_year <- movies %>% group_by(release_year) %>% summarize(avgSales = mean(world_sales_mil))
ggplot(by_year, aes(x = release_year, y = avgSales)) + geom_point() + geom_smooth() + scale_x_discrete(name = "Year", breaks=seq(min(by_year$release_year),max(by_year$release_year),10)) + scale_y_continuous(name = "Average Sales (in millions)", breaks=seq(0,max(by_year$avgSales), 50))
```